tasks:
  - init: ./gradlew build
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - fwcd.kotlin@0.2.11:hnLDbpwnjyb7P7BCkc2Ykg==
    - wpilibsuite.vscode-wpilib@2020.3.2:RAxZwFw1Ra3mIl+oIDddXg==